name: Node.js CI with Coverage Report

on:
  pull_request:
    branches:
      - "main" 

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests and generate coverage report
        run: npm run test -- --coverage

      - name: Set up Git for authentication
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          # Ensure HTTPS is used with the GITHUB_TOKEN for authentication
          git config --global url."https://${{ secrets.GH_TOKEN }}@github.com/".insteadOf "https://github.com/"
        
      - name: Deploy coverage report to GitHub Pages
        run: |
          # Install 'gh-pages' to deploy coverage to GitHub Pages
          npm install --save-dev gh-pages
          
          # Build the coverage report directory (usually in 'coverage/lcov-report')
          mkdir -p public
          cp -r coverage/lcov-report/* public/
          
          # Publish the report to the gh-pages branch
          npx gh-pages -d public
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}  # Pass GITHUB_TOKEN as environment variable
